let appDiv = document.getElementById("app");

const model = {
	app: {
		loginPage: "Login",
		registerPage: "Register",
		homePage: "Home",
	},
	input: {
		credentialsLogin: {
			username: "Terje",
			password: "startcoding",
		},
		credentialsRegister: {
			username: "",
			email: "",
			password: "",
			passwordConfirm: "",
			age: "",
			groups: [
				{
					id: 5,
					name: "Group 1",
					members: [
						{ name: "Elisabeth", age: 30 },
						{ name: "Emil", age: 29 },
						{ name: "Erik", age: 27 },
						{ name: "Even", age: 26 },
					],
				},
				{
					id: 8,
					name: "Group 2",
					members: [
						{ name: "Flemming", age: 30 },
						{ name: "Geir", age: 29 },
						{ name: "Harald", age: 27 },
					],
				},
				{
					id: 9,
					name: "Group 3",
					members: [
						{ name: "Jonas", age: 30 },
						{ name: "Karsten", age: 29 },
						{ name: "Kasper", age: 27 },
					],
				},
			],
		},
	},
	data: {
		users: [
			{
				id: 1,
				email: "",
				username: "Terje",
				password: "startcoding",
				age: 50,
				groups: [
					{
						id: 4,
						name: "Group 1",
						members: [
							{ name: "Adrian", age: 30 },
							{ name: "Alexander", age: 29 },
							{ name: "Anders", age: 27 },
						],
					},
					{
						id: 6,
						name: "Group 2",
						members: [
							{ name: "Asbjørn", age: 30 },
							{ name: "Bjørn", age: 29 },
							{ name: "Carina", age: 27 },
						],
					},
					{
						id: 7,
						name: "Group 3",
						members: [
							{ name: "Chris", age: 30 },
							{ name: "Christoffer", age: 29 },
							{ name: "Danica", age: 27 },
							{ name: "Daniel", age: 23 },
							{ name: "Eirik", age: 30 },
						],
					},
					{
						id: 10,
						name: "Group 4",
						members: [
							{ name: "Chris", age: 30 },
							{ name: "Christoffer", age: 29 },
							{ name: "Danica", age: 27 },
							{ name: "Daniel", age: 23 },
							{ name: "Eirik", age: 30 },
						],
					},
				],
			},
			{
				id: 2,
				email: "",
				username: "Bjørnar",
				password: "dontStressMeowth",
				age: 27,
				groups: [
					{
						id: 5,
						name: "Group 1",
						members: [
							{ name: "Bayan", age: 30 },
							{ name: "John Espen", age: 29 },
							{ name: "Kenneth", age: 27 },
							{ name: "Marius", age: 26 },
							{ name: "Tomas", age: 24 },
						],
					},
					{
						id: 8,
						name: "Group 2",
						members: [
							{ name: "Terje", age: 30 },
							{ name: "Elin", age: 29 },
							{ name: "Emil", age: 27 },
							{ name: "Erlend", age: 26 },
						],
					},
					{
						id: 9,
						name: "Group 3",
						members: [
							{ name: "Joakim", age: 30 },
							{ name: "Lise", age: 29 },
							{ name: "Stella", age: 27 },
						],
					},
				],
			},
			{
				id: 3,
				email: "",
				username: "Eskil",
				age: 45,
				groups: [],
			},
			{
				id: 4,
				email: "",
				username: "Linn",
				age: 40,
				groups: [],
			},
			{
				id: 5,
				email: "admin@admin.admin",
				username: "admin",
				password: "admin",
				age: 1,
				groups: [
					{
						id: 1,
						name: "Group 1",
						members: [
							{ name: "Joakim", age: 20 },
							{ name: "Kristian", age: 19 },
							{ name: "Stian", age: 24 },
						],
					},
					{
						id: 2,
						name: "Group 2",
						members: [
							{ name: "Marius", age: 27 },
							{ name: "Christian", age: 31 },
						],
					},
					{
						id: 3,
						name: "Group 3",
						members: [
							{ name: "Andreas", age: 30 },
							{ name: "Kristoffer", age: 29 },
							{ name: "Mikkel", age: 2021 },
							{ name: "Stigh", age: 26 },
							{ name: "Vanja", age: 24 },
						],
					},
				],
			},
		],
		filters: [
			{ cost: true },
			{ indoors: false },
			{ city: false },
			{ Winter: false },
			{ physicalUpperbody: false },
			{ physicalLowerbody: false },
		],
		activities: [
			{
				name: "Go for a walk",
				cost: false,
				indoors: false,
				physicalUpperBody: false,
				physicalLowerbody: true,
			},
			{
				name: "Go for a run",
				cost: false,
				indoors: false,
				physicalLowerbody: true,
			},
			{
				name: "Go to the gym",
				cost: false,
				indoors: true,
				city: true,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Cross-country skiing",
				cost: false,
				indoors: false,
				city: false,
				winter: true,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Downhill-skiing",
				cost: true,
				indoors: false,
				city: false,
				winter: true,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Bikeride",
				cost: false,
				indoors: false,
				winter: false,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Go for a swim",
				cost: false,
				city: false,
				winter: false,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Rockclimbing",
				cost: true,
				indoors: true,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Play tennis",
				cost: true,
				city: false,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Go bowling",
				cost: true,
				indoors: true,
				city: true,
				physicalUpperBody: true,
				physicalLowerbody: false,
			},
			{
				name: "Go to the cinema",
				cost: true,
				indoors: true,
				city: true,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
			{
				name: "Go to an Escape Room",
				cost: true,
				indoors: true,
				city: true,
				physicalUpperBody: false,
				physicalLowerbody: true,
			},
			{
				name: "Play squash",
				cost: true,
				city: true,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Go to a concert",
				cost: true,
				indoors: false,
				city: true,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
			{
				name: "Play some board games",
				cost: false,
				indoors: true,
				physicalUpperBody: true,
				physicalLowerbody: false,
			},
			{
				name: "Play a game of cards",
				cost: false,
				indoors: true,
				city: false,
				physicalUpperBody: true,
				physicalLowerbody: false,
			},
			{
				name: "Go on a fishing trip",
				cost: false,
				indoors: false,
				city: false,
				physicalUpperBody: true,
				physicalLowerbody: false,
			},
			{
				name: "Go camping",
				cost: false,
				indoors: false,
				city: false,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
			{
				name: "Go to the theatre",
				cost: true,
				indoors: true,
				city: true,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
			{
				name: "Play golf",
				cost: true,
				indoors: false,
				city: false,
				winter: false,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Go play minigolf",
				cost: true,
				indoors: false,
				city: true,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Go on a road-trip",
				cost: false,
				indoors: false,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
			{
				name: "Go to the beach",
				cost: false,
				indoors: false,
				winter: false,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
			{
				name: "Go ice-skating",
				cost: true,
				winter: true,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Grab something to eat",
				cost: true,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
			{
				name: "Sing some karaoke",
				cost: true,
				indoors: true,
				city: true,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
			{
				name: "Play paintball",
				cost: true,
				indoors: false,
				winter: false,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Play lasertag",
				cost: true,
				indoors: true,
				city: true,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Go shopping",
				cost: true,
				city: true,
				physicalUpperBody: false,
				physicalLowerbody: true,
			},
			{
				name: "Go on a boat ride",
				cost: false,
				indoors: false,
				city: false,
				winter: false,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
			{
				name: "Go to an amusementpark",
				cost: true,
				indoors: false,
				city: false,
				physicalUpperBody: false,
				physicalLowerbody: true,
			},
			{
				name: "Visit a museum",
				cost: true,
				indoors: true,
				city: true,
				physicalUpperBody: false,
				physicalLowerbody: true,
			},
			{
				name: "Visit a zoo",
				cost: true,
				indoors: false,
				city: false,
				winter: false,
				physicalUpperBody: false,
				physicalLowerbody: true,
			},
			{
				name: "Play shuffleboard",
				cost: true,
				indoors: true,
				city: true,
				physicalUpperBody: true,
				physicalLowerbody: false,
			},
			{
				name: "Go to the carnival",
				cost: true,
				indoors: false,
				city: true,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
			{
				name: "Go rollerblading",
				cost: false,
				indoors: false,
				city: false,
				winter: false,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Grab a coffee",
				cost: true,
				indoors: true,
				city: true,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
			{
				name: "Go GeoCaching",
				cost: false,
				indoors: false,
				city: false,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Bake something tasty",
				cost: false,
				indoors: true,
				city: false,
				physicalUpperBody: true,
				physicalLowerbody: false,
			},
			{
				name: "Paint a picture",
				cost: true,
				indoors: true,
				city: false,
				physicalUpperBody: true,
				physicalLowerbody: false,
			},
			{
				name: "Go bungee-jumping",
				cost: true,
				indoors: false,
				city: false,
				winter: false,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Play snooker",
				cost: true,
				indoors: true,
				city: true,
				winter: true,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Go skydiving!",
				cost: true,
				indoors: false,
				city: false,
				winter: false,
				physicalUpperBody: true,
				physicalLowerbody: true,
			},
			{
				name: "Go to a flee-market",
				cost: true,
				physicalUpperBody: false,
				physicalLowerbody: false,
			},
		],
	},
};
