const { type } = require("os");

const model = {
	app: {
		loginPage: "Login",
		registerPage: "Register",
		homePage: "Home",
	},
	input: {
		credentialsLogin: {
			username: "",
			password: "",
		},
		credentialsRegister: {
			email: "",
			username: "",
			password: "",
		},
	},
	users: [
		{
			username: "Terje",
			password: "startcoding",
			userinformation: {
				age: 28,
				grupper: {
					eksempelgruppe: [
						{ member1: "Eskil", alder: 27, tilstede: true },
						{ member2: "Terje", alder: 52, tilstede: true },
						{ member3: "Linn", alder: 40, tilstede: true },
						{ member4: "Bjørnar", alder: 31, tilstede: true },
					],
				},
			},
		},
		{
			username: "Bjørnar",
			password: "dontStressMeowth",
			userinformation: {
				age: 2,
				grupper: {
					eksempelgruppe: [
						{ member1: "Joakim", aler: 25, tilstede: true },
						{ member2: "Anita", aler: 36, tilstede: true },
						{ member3: "Elin", aler: 21, tilstede: true },
						{ member4: "Erlend", aler: 12, tilstede: true },
					],
				},
			},
		},
	],
	filters: [
		{ cost: true },
		{ indoors: false },
		{ city: false },
		{ Winter: false },
		{ physicalUpperbody: false },
		{ physicalLowerbody: false },
	],
	activities: [
		{
			name: "Walk",
			cost: false,
			indoors: false,
			winter: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Go to the gym",
			cost: true,
			indoors: true,
			city: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Go for a run",
			cost: false,
			indoors: false,
			winter: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Cross-country skiing",
			cost: false,
			indoors: false,
			city: false,
			winter: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Slalom",
			cost: true,
			indoors: false,
			city: false,
			winter: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Bikeride",
			cost: false,
			indoors: false,
			winter: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Clean",
			cost: false,
			indoors: true,
			city: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Swimming-pool",
			cost: true,
			indoors: true,
			city: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Go for a swim",
			cost: false,
			indoors: false,
			city: false,
			winter: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Rockclimbing",
			cost: true,
			indoors: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Play tennis",
			cost: true,
			city: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Go bowling",
			cost: true,
			indoors: true,
			city: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: false,
		},
		{
			name: "Go to the cinema",
			cost: true,
			indoors: true,
			city: true,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
		{
			name: "Go to an Escape Room",
			cost: true,
			indoors: true,
			city: true,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
		{
			name: "Play squash",
			cost: true,
			city: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Go to a concert",
			cost: true,
			indoors: false,
			city: true,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
		{
			name: "Play some board games",
			cost: false,
			indoors: true,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
		{
			name: "Play a game of cards",
			cost: false,
			indoors: true,
			city: false,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
		{
			name: "Go on a fishing trip",
			cost: true,
			indoors: false,
			city: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: false,
		},
		{
			name: "Go camping",
			cost: true,
			indoors: false,
			city: false,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
		{
			name: "Go to the theatre",
			cost: true,
			indoors: true,
			city: true,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		}, //play/musical etc
		{
			name: "Play golf",
			cost: true,
			indoors: false,
			city: false,
			winter: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Go play minigolf",
			cost: true,
			indoors: false,
			city: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Go on a road-trip",
			cost: false,
			indoors: false,
			city: false,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
		{
			name: "Go to the beach",
			cost: false,
			indoors: false,
			city: false,
			winter: false,
			physicalphysicalUpperbody: false,
			physicalLowerbody: true,
		},
		{
			name: "Go ice-skating",
			cost: true,
			winter: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Grab something to eat",
			cost: true,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
		{
			name: "Sing some karaoke",
			cost: true,
			indoors: true,
			city: true,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
		{
			name: "Play paintball",
			cost: true,
			indoors: false,
			city: true,
			winter: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Play lasertag",
			cost: true,
			indoors: true,
			city: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Go shopping",
			cost: true,
			indoors: false,
			city: true,
			physicalphysicalUpperbody: false,
			physicalLowerbody: true,
		},
		{
			name: "Go on a boat ride",
			cost: false,
			indoors: false,
			city: false,
			winter: false,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
		{
			name: "Go to an amusementpark",
			cost: true,
			indoors: false,
			city: false,
			physicalphysicalUpperbody: false,
			physicalLowerbody: true,
		},
		{
			name: "Visit a museum",
			cost: true,
			indoors: true,
			city: true,
			physicalphysicalUpperbody: false,
			physicalLowerbody: true,
		},
		{
			name: "Visit a zoo",
			cost: true,
			indoors: false,
			city: false,
			winter: false,
			physicalphysicalUpperbody: false,
			physicalLowerbody: true,
		},
		{
			name: "Play shuffleboard",
			cost: true,
			indoors: true,
			city: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: false,
		},
		{
			name: "Go to the carnival",
			cost: true,
			indoors: false,
			city: true,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
		{
			name: "Go rollerblading",
			cost: false,
			indoors: false,
			city: false,
			winter: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Grab a coffee",
			cost: true,
			indoors: true,
			city: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: false,
		},
		{
			name: "Go GeoCaching",
			cost: false,
			indoors: false,
			city: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Bake something tasty",
			cost: false,
			indoors: true,
			city: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: false,
		},
		{
			name: "Paint a picture",
			cost: true,
			indoors: true,
			city: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: false,
		},
		{
			name: "Go bungee-jumping",
			cost: true,
			indoors: false,
			city: false,
			winter: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Play snooker",
			cost: true,
			indoors: true,
			city: true,
			winter: true,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Go skydiving!",
			cost: true,
			indoors: false,
			city: false,
			winter: false,
			physicalphysicalUpperbody: true,
			physicalLowerbody: true,
		},
		{
			name: "Go to a flee-market",
			cost: true,
			indoors: false,
			physicalphysicalUpperbody: false,
			physicalLowerbody: false,
		},
	],
	// DATA
	// aktiviteter
};

//aktiviteter
//  blablabla
//      filtere

//{ username: "Elin", password: "1234", age: "", admin: true },
//{ username: "Elin", password: "1234" },
//{ username: "Elin", password: "1234" },
